apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  namespace: dev
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      serviceAccount: server
      containers:
      - name: server
        image: "melquiadesrodrigues/hello-go:v5.5"
        resources:
          limits:
            memory: "12Mi"
            cpu: "1m"
