apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "melquiadesrodrigues/hello-go:v5.5"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 30
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
            # - mountPath: "/go/pvc"
            #   name: goserver-volume
          resources:
            limits:
              memory: 25Mi
              cpu: "0.3"
            requests:
              memory: 20Mi
              cpu: "0.05"
      volumes:
        # - name: goserver-pvc
        #   persistentVolumeClaim:
        #     claimName: goserver-pvc
        - name: config
          configMap:
            name: goserver-family
            items: 
            - key: members
              path: "family.txt"